Routing correcting
Lambda-School-Labs/life-logger-fe pull request #91
Opened 2020-07-07 01:44 UTC by Wade-Coplen

# Description
Small correction to ensure the landing page is going to the signin/signup page.
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [x ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?
No
- [ ] Test A
- [ ] Test B

# Checklist

- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x ] There are no merge conflicts

2020-07-07 03:30 UTC, Carrillo9Ana approved these changes
looks good

2020-07-14 01:29 UTC, jgarrow commented on src/App.js
> +      <Router>
The `development` branch has `App` wrapped in the `Router` up a level in the `index.js` file, so you don't need to wrap it in a `Router` again here

2020-07-14 01:30 UTC, jgarrow commented on src/components/LandingPage.js
> +      <Link to="/SignUp">
🙌

2020-07-14 01:35 UTC, jgarrow requested changes
I would pull from the `development` branch and merge any conflicts first since it's been a while. And we don't need to wrap everything in a `Router` in the `App.js` file since that component is already wrapped in it in the `index.js` file. But other than that, I think it looks good!

2020-07-16 02:09 UTC, JaxAtwood approved these changes

2020-07-16 02:15 UTC, davidmoates approved these changes

2020-07-16 02:26 UTC, jgarrow commented on src/components/LandingPage.js
> +      <Link to="/SignUp">
Capitalization of this url doesn't match the one in the Route in App.js

2020-07-16 02:35 UTC, jgarrow requested changes
The `to` path in `LandingPage.js` doesn't match the one in `App.js` for the signup

2020-07-16 02:49 UTC, merged

2021-03-23 02:22 UTC, tinomen reviewed
OK